version: '3.8'
services:
  orderservice:
    build: .
    ports:
      - "8082:8082"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://orderservice-db:27017/orderservice
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - mynetwork
    depends_on:
      - orderservice-db
      - kafka

  orderservice-db:
    image: mongo:5.0
    ports:
      - "27018:27017"
    networks:
      - mynetwork

  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9092
      KAFKA_LISTENER_NAME: INSIDE
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - mynetwork

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
    networks:
      - mynetwork

networks:
  mynetwork: